import type { RepositoryStatus } from "@/types/repository";

export const sampleRepositories: RepositoryStatus[] = [
  {
    name: "api-gateway",
    path: "/Users/user/workspace/api-gateway",
    currentBranch: "main",
    isClean: true,
    modifiedCount: 0,
    stagedCount: 0,
    untrackedCount: 0,
    ahead: 0,
    behind: 0,
    hasUpstream: true,
    lastCommitHash: "9a4f210",
    lastCommitMessage: "Harden health check routing",
    lastCommitAuthor: "RepoPilot",
    lastCommitTime: "32 minutes ago",
    remoteUrl: "git@github.com:team/api-gateway.git",
    lastScannedAt: new Date().toISOString(),
    error: null,
  },
  {
    name: "web-console",
    path: "/Users/user/workspace/web-console",
    currentBranch: "feature/dashboard",
    isClean: false,
    modifiedCount: 4,
    stagedCount: 1,
    untrackedCount: 0,
    ahead: 2,
    behind: 0,
    hasUpstream: true,
    lastCommitHash: "c18d04b",
    lastCommitMessage: "Add repository summary cards",
    lastCommitAuthor: "RepoPilot",
    lastCommitTime: "2 hours ago",
    remoteUrl: "git@github.com:team/web-console.git",
    lastScannedAt: new Date().toISOString(),
    error: null,
  },
  {
    name: "docs-site",
    path: "/Users/user/workspace/docs-site",
    currentBranch: "main",
    isClean: false,
    modifiedCount: 0,
    stagedCount: 0,
    untrackedCount: 3,
    ahead: 0,
    behind: 3,
    hasUpstream: true,
    lastCommitHash: "d7190aa",
    lastCommitMessage: "Refresh setup guide",
    lastCommitAuthor: "RepoPilot",
    lastCommitTime: "yesterday",
    remoteUrl: null,
    lastScannedAt: new Date().toISOString(),
    error: null,
  },
];
